import AppKit

/// Notices when anything is copied. macOS has no clipboard notification, so
/// the pasteboard's change count is checked a few times a second. Reading a
/// counter costs next to nothing; the contents are only read when it moves.
@MainActor
final class ClipboardWatcher {
    /// Written next to Pinwire's own copies, so a click on the line does
    /// not hang the same thing again.
    nonisolated static let ownType = NSPasteboard.PasteboardType("app.pinwire.own")

    /// Types that mark a copy as private or throwaway, following
    /// nspasteboard.org. Password managers set these, and so does any app
    /// that does not want its copy kept in a history.
    static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        ownType.rawValue,
    ]

    /// Apps whose copies are never kept.
    private static let skipApps: Set<String> = [
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
    ]

    private static let interval: TimeInterval = 0.5

    private let pasteboard = NSPasteboard.general
    private let onCopy: (Clip) -> Void
    private var lastChange: Int
    private var timer: Timer?

    init(onCopy: @escaping (Clip) -> Void) {
        self.onCopy = onCopy
        lastChange = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        // What was on the clipboard before is not a new copy.
        lastChange = pasteboard.changeCount
        let timer = Timer(timeInterval: Self.interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        // Lets macOS batch the wakeups with others, which saves energy.
        timer.tolerance = Self.interval / 2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Whether macOS has been told, in Privacy & Security, never to let
    /// Pinwire read the clipboard. Reading then does nothing, so the menu
    /// says so instead of pretending to work.
    var isBlocked: Bool {
        if #available(macOS 15.4, *) { return pasteboard.accessBehavior == .alwaysDeny }
        return false
    }

    private func check() {
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        guard !isBlocked else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard !types.isEmpty, types.isDisjoint(with: Self.skipTypes) else { return }
        // The app in front now: usually the one that copied. It is only a
        // label and a second filter; the private markers above are the rule.
        let app = NSWorkspace.shared.frontmostApplication
        if let id = app?.bundleIdentifier, Self.skipApps.contains(id) { return }
        // A screenshot copied with Control held already hangs from its file
        // when it is saved; one copied straight to the clipboard hangs here.
        guard let clip = Clip.capture(from: pasteboard, source: app?.localizedName,
                                      skipping: Self.skipTypes) else { return }
        onCopy(clip)
    }
}
